name: clipped_shac
network_config_filename: clipped_shac_network_config.json
module_path: brax.training.agents.clipped_shac.train
checkpoint_path: brax.training.agents.clipped_shac.checkpoint
checkpoint_keyword_arg: save_checkpoint_path
include_time: ${env.include_time}

network_factory_path: brax.training.agents.clipped_shac.networks
make_network_fn_name: make_shac_networks
make_inference_fn_name: make_inference_fn

params:
  include_time: ${env.include_time}

  # schedule parameters
  num_timesteps: ${env.config.num_timesteps}
  unroll_length: ${env.clipped_shac.unroll_length}
  batch_size: ${env.clipped_shac.batch_size}
  num_minibatches: ${env.clipped_shac.num_minibatches}
  num_updates_per_batch: ${env.clipped_shac.num_updates_per_batch}

  # environment wrapper
  num_envs: ${env.clipped_shac.num_envs}
  episode_length: ${env.config.episode_length}
  action_repeat: ${env.config.action_repeat}

  # network parameters
  actor_grad_norm: ${env.config.actor_grad_norm}
  critic_grad_norm: ${env.config.critic_grad_norm}
  lr_schedule: ${env.config.lr_schedule}
  actor_lr: ${env.clipped_shac.actor_lr}
  critic_lr: ${env.clipped_shac.critic_lr}
  tau: ${env.config.tau}
  betas: ${env.config.betas}

  # SHAC params
  deterministic_train: false
  discounting: ${env.config.discounting}
  normalize_observations: ${env.config.normalize_observations}
  reward_scaling: ${env.clipped_shac.reward_scaling}
  gae_lambda: ${env.config.gae_lambda}

  # eval
  num_evals: ${env.config.num_evals}
  num_eval_envs: ${env.config.num_eval_envs}
  deterministic_eval:  ${env.config.deterministic_eval}

network_factory_params:
  policy_hidden_layer_sizes: ${env.config.policy_hidden_layer_sizes}
  value_hidden_layer_sizes: ${env.config.value_hidden_layer_sizes}
  dtype: ${env.dtype}
