name: dual_apg
network_config_filename: dual_apg_network_config.json
module_path: brax.training.agents.dual_apg.train
checkpoint_path: brax.training.agents.dual_apg.checkpoint
checkpoint_keyword_arg: save_checkpoint_path

network_factory_path: brax.training.agents.dual_apg.networks
make_network_fn_name: make_apg_networks

params:
  # schedule parameters
  num_timesteps: ${env.config.num_timesteps}
  unroll_length: ${env.dual_apg.unroll_length}
  batch_size: ${env.dual_apg.batch_size}
  num_minibatches: ${env.dual_apg.num_minibatches}
  num_updates_per_batch: ${env.dual_apg.num_updates_per_batch}

  # environment wrapper
  num_envs: ${env.dual_apg.num_envs}
  episode_length: ${env.config.episode_length}
  action_repeat: ${env.config.action_repeat}

  # network parameters
  actor_grad_norm: ${env.config.actor_grad_norm}
  critic_grad_norm: ${env.config.critic_grad_norm}
  actor_lr: ${env.dual_apg.actor_lr}
  critic_lr: ${env.dual_apg.critic_lr}
  tau: ${env.config.tau}
  betas: ${env.config.betas}

  # SHAC params
  discounting: ${env.config.discounting}
  normalize_observations: ${env.config.normalize_observations}
  reward_scaling: ${env.config.reward_scaling}

  # eval
  num_evals: ${env.config.num_evals}
  num_eval_envs: ${env.dual_apg.num_envs}
  deterministic_eval:  ${env.config.deterministic_eval}

network_factory_params:
  policy_hidden_layer_sizes: ${env.config.policy_hidden_layer_sizes}
  value_hidden_layer_sizes: ${env.config.value_hidden_layer_sizes}
  dtype: ${env.dtype}
