name: ppo
network_config_filename: ppo_network_config.json
module_path: brax.training.agents.ppo.train
checkpoint_path: brax.training.agents.ppo.checkpoint
checkpoint_keyword_arg: save_checkpoint_path

params:
  num_timesteps: 50_000_000
  num_evals: 20
  reward_scaling: 5
  episode_length: 1000
  normalize_observations: True
  action_repeat: 1
  unroll_length: 30
  num_minibatches: 16
  num_updates_per_batch: 8
  discounting: 0.95
  learning_rate: 3e-4
  entropy_cost: 1e-2
  num_envs: 2048
  batch_size: 512
