name: fingers_ball
terminal_reward_name: fingers_ball
include_time: true
dtype: float64

kwargs:
  eps: 1e-6
  # reward_shaping: true

config:
  # schedule parameters
  num_timesteps: 6_553_600

  # environment wrapper
  episode_length: 1_000
  action_repeat: 1

  # network parameters
  actor_grad_norm: 1.0
  critic_grad_norm: 1.0
  lr_schedule: constant
  policy_hidden_layer_sizes: [64, 64]
  value_hidden_layer_sizes: [64, 64]
  tau: 0.8
  betas: [0.7, 0.95]

  # SHAC params
  entropy_cost: 1e-2
  discounting: 1.0
  normalize_observations: True
  reward_scaling: 1
  gae_lambda: 0.95

  # eval
  num_evals: 20
  num_eval_envs: 128
  deterministic_eval: True

# sac:
#   batch_size: 512
#   grad_updates_per_step: 64
#   num_envs: 128

#   max_replay_size: 1048576
#   min_replay_size: 8192

#   learning_rate: 6e-4

# ppo:
#   unroll_length: 5
#   batch_size: 1024
#   num_minibatches: 32
#   num_updates_per_batch: 4
#   num_envs: 128

#   learning_rate: 6e-4

diffrl_shac:
  unroll_length: 32
  batch_size: 1024
  num_minibatches: 4
  num_updates_per_batch: 16
  num_envs: 2048

  actor_lr: 2e-3
  critic_lr: 1e-4

unroll_apg:
  batch_size: 1024
  num_envs: 1024

  learning_rate: 1e-3

deterministic_apg:
  batch_size: 2048
  num_envs: 2048

  learning_rate: 2e-4
